# Generated by Django 5.2.4 on 2025-07-28 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('dates', 'Dates'), ('event', 'Events'), ('people', 'People'), ('places', 'Places'), ('themes', 'Themes'), ('topics', 'Topics')], default='dates', max_length=20)),
                ('entry_count', models.IntegerField(default=0)),
                ('entries', models.ManyToManyField(related_name='tags', to='core.entry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
