# Generated by Django 5.2.4 on 2025-07-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('dates', 'Dates'), ('events', 'Events'), ('people', 'People'), ('places', 'Places'), ('themes', 'Themes'), ('topics', 'Topics')], default='dates', max_length=20),
        ),
    ]
