# Generated by Django 5.2.4 on 2025-07-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_entry_title_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='entry_count',
            field=models.IntegerField(default=1),
        ),
    ]
