# Generated by Django 5.2.4 on 2025-07-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tag_entry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('dates', 'Dates'), ('events', 'Events'), ('people', 'People'), ('places', 'Places'), ('themes', 'Themes'), ('topics', 'Topics')], max_length=20),
        ),
    ]
