# Generated by Django 5.2.4 on 2025-07-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_alter_tag_entry_count_paragraph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='content',
            new_name='body',
        ),
    ]
