# Generated by Django 5.2.4 on 2025-07-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_letter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='date_sent',
            new_name='date',
        ),
    ]
