# Generated by Django 5.2.4 on 2025-07-31 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_date_sent_letter_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='sender',
        ),
    ]
