# Generated by Django 5.2.4 on 2025-07-31 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_letter_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.item')),
                ('time', models.CharField(blank=True, max_length=100)),
                ('servings', models.CharField(blank=True, max_length=50)),
                ('ingredients', models.TextField(help_text='Only one ingredient per line!')),
                ('directions', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.item',),
        ),
    ]
