# Generated by Django 5.2.4 on 2025-08-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_technical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical',
            name='body',
            field=models.TextField(help_text='Enter LaTeX display math without any newline characters.'),
        ),
    ]
